import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { background } from "@chakra-ui/react";
import dynamic from "next/dynamic";
const DynamicAntdLayout = dynamic(() => import('@/app/components/defaultLayout'), { ssr: false });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body>
      <AntdRegistry>
          <DynamicAntdLayout>
            {children}
          </DynamicAntdLayout>
        </AntdRegistry>
      </body>
    </html>
  );
}
